### ISSUE TITLE
Drawing Graph

### ISSUE THREAD

**Issue by ActivateDZA** [raidancampbell/Cowrie-Analyzer#1]
Hi,

I am currently using your python script to analyse some crowrie logs that I have. I get the following error:
Traceback (most recent call last):
  File "CowrieAnalyzer.py", line 120, in <module>
    CowrieAnalyzer().run()
  File "CowrieAnalyzer.py", line 92, in run
    self.plot()
  File "CowrieAnalyzer.py", line 44, in plot
    dates, ssh_attempts = zip(*sorted(self.ssh_times_cnt.items()))
ValueError: not enough values to unpack (expected 2, got 0)

the logs does not have SSH traffic. What can I change to make the python script to create the graph

**Comment by raidancampbell** [comment]
delete or comment out the following two lines:

```
        dates, ssh_attempts = zip(*sorted(self.ssh_times_cnt.items()))
        ax.plot(dates, ssh_attempts, 'b-', label='SSH Attempts')
```

**Comment by ActivateDZA** [comment]
Thank you that fixed the issue.
